language: ruby
script:
- git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
- .forge-releng/publish
rvm:
- 1.8.7
- 1.9.3-p484
- 2.0.0
bundler_args: ''
notifications:
  email:
  - tfhartmann@gmail.com
  hipchat:
    rooms:
      secure: gChdWNxhZ4XQS+We5d4XRxz53shln62wz45OTa5teBZP+6Urhwv4ZmOa+F7LHJLytcnS40R8CWaKXXmdo8e+yKIKpJjvIAlSNDT7wSPb4uL+bJZEQDfkQ6Oknliuzy6tP9Dy62Z9Ms4IH58QA6zfOj9ibxb6r9/2XRFSuVZAMN4=
env:
  matrix:
  - PUPPET_VERSION=3.5.0
  - PUPPET_VERSION=3.4.2
  - PUPPET_VERSION=3.3.1
  - PUPPET_VERSION=3.2.3
  - PUPPET_VERSION=2.7.21
  global:
  - PUBLISHER_LOGIN=huit
  - secure: Ijc9NOKcofDC+i0afauvFj7P6vqtThbeMnjuOYxaqcMPfM4f+IrxpzyoIjOzDbD83b0vMYCSItPW/RExVINkwhjghfzPhMsbjfA2XfcvWYMxCOsvXR3TMHSNyPGD7ITbitUDofJ0TTIfZQwE10SeI8MhfL61a4eiR2QNQhDyraI=
  - secure: GZ6bDkhjFnEsyazZJQfDtWYhNyXxqLok6YH8fRgWU6Y3tIfJ9bYqne/s/aUOI06pfafeRHQTK7CkJwn+H5GPZtPdw9HU6rTkqjQKPjNN34y4Gdkgw8ptY6t5LPqZZT4xD51J1JOOrCjEyKor1XDYrQBftLE1jJnquzDzaFwhPOc=
